import { CanonicalMedia } from "./local-export";

export const demoItems: CanonicalMedia[] = [
  {
    media_type: "movie",
    source_platform: "douban",
    source_id: "1292052",
    collection_status: "completed",
    titles: { en: "The Shawshank Redemption" },
    year: 1994,
    release_date: "1994-09-10",
    countries: ["United States"],
    rating: { value: 5, scale: 5 },
    consumed_date: "2024-04-01",
    tags: ["mobile-test", "top250"],
    external_ids: { imdb: "tt0111161" },
  },
  {
    media_type: "movie",
    source_platform: "douban",
    source_id: "1291557",
    collection_status: "completed",
    titles: { en: "In the Mood for Love" },
    year: 2000,
    release_date: "2000-09-29",
    countries: ["Hong Kong"],
    rating: { value: 4.5, scale: 5 },
    consumed_date: "2024-04-02",
    tags: ["mobile-test", "hong-kong"],
    external_ids: { imdb: "tt0118694" },
  },
  {
    media_type: "movie",
    source_platform: "douban",
    source_id: "1308857",
    collection_status: "watchlist",
    titles: { en: "2046" },
    year: 2004,
    rating: null,
    marked_date: "2024-04-04",
    tags: ["mobile-test", "watchlist"],
    external_ids: {},
  },
  {
    media_type: "book",
    source_platform: "douban",
    source_id: "2567698",
    collection_status: "completed",
    titles: { en: "The Three-Body Problem" },
    year: 2008,
    release_date: "2008",
    creators: ["Liu Cixin"],
    rating: { value: 5, scale: 5 },
    consumed_date: "2024-04-03",
    tags: ["mobile-test", "sci-fi"],
    external_ids: { isbn: "9787536692930", author: "Liu Cixin" },
  },
];
